In [1]:
#Load and pre-proccess data
import pandas as pd
inputFolder = 'data/'
df = pd.read_csv(inputFolder + 'iris.csv')
print(df.head())

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa


In [2]:
#Split data into features and target
X = df.loc[:, df.columns != 'species']
print(X.head())
y = df['species']
print(y.head())

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2
0    setosa
1    setosa
2    setosa
3    setosa
4    setosa
Name: species, dtype: object


In [3]:
#Split data into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25)
print(X_train.shape)
print(X_train.head())
print(X_test.shape)
print(X_test.head())
print(y_train.shape)
print(y_train.head())
print(y_test.shape)
print(y_test.head())

(112, 4)
     sepal_length  sepal_width  petal_length  petal_width
29            4.7          3.2           1.6          0.2
115           6.4          3.2           5.3          2.3
67            5.8          2.7           4.1          1.0
107           7.3          2.9           6.3          1.8
82            5.8          2.7           3.9          1.2
(38, 4)
     sepal_length  sepal_width  petal_length  petal_width
77            6.7          3.0           5.0          1.7
121           5.6          2.8           4.9          2.0
32            5.2          4.1           1.5          0.1
65            6.7          3.1           4.4          1.4
1             4.9          3.0           1.4          0.2
(112,)
29         setosa
115     virginica
67     versicolor
107     virginica
82     versicolor
Name: species, dtype: object
(38,)
77     versicolor
121     virginica
32         setosa
65     versicolor
1          setosa
Name: species, dtype: object


In [4]:
#Model creation
from sklearn.ensemble import RandomForestClassifier
#create object of RandomForestClassifier 
model = RandomForestClassifier()

In [5]:
#Training

#train model
model.fit(X_train, y_train)
#print score
model.score(X_train,y_train)

1.0

In [6]:
#Predict
#predict X_test data
predictions = model.predict(X_test)
predictions[:10]


array(['virginica', 'virginica', 'setosa', 'versicolor', 'setosa',
       'versicolor', 'virginica', 'versicolor', 'virginica', 'versicolor'],
      dtype=object)

In [7]:
#Scoring
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

0.9473684210526315
[[10  0  0]
 [ 0 15  1]
 [ 0  1 11]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       0.94      0.94      0.94        16
   virginica       0.92      0.92      0.92        12

    accuracy                           0.95        38
   macro avg       0.95      0.95      0.95        38
weighted avg       0.95      0.95      0.95        38



In [13]:
#Saving model
#We are using joblib model to serialize Python object. joblib.dump() will allow to save Python object on disk.
#save model in output directory
import joblib as joblib
joblib.dump(model,'output/randomforest_model.pkl')


['output/randomforest_model.pkl']

In [14]:
#Predict with new data

import numpy as np
test_data = [5.1, 3.2, 1.5, 0.4]
#convert test_data into numpy array
test_data = np.array(test_data)
#reshape
test_data = test_data.reshape(1,-1)
print(test_data)


[[5.1 3.2 1.5 0.4]]


In [15]:
#Load trained model
#declare path where you saved your model
outFileFolder = ''
filePath = outFileFolder + 'output/randomforest_model.pkl'
#open file
file = open(filePath, "rb")
#load the trained model
trained_model = joblib.load(file)

In [16]:
#Predict with trained model
prediction = trained_model.predict(test_data)
print(prediction)

['setosa']
